language: scala
sudo: false
dist: xenial
jdk: openjdk8
scala:
- 2.12.8
- 2.11.12
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/launchers"
script:
- sbt "++${TRAVIS_SCALA_VERSION}! -v" test
before_cache:
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
